### ISSUE TITLE
Sample Project?

### ISSUE THREAD

**Issue by JulianG** [BrettJephson/ash-js#4]
Hi Brett,
Do you have a sample project showing how to use the framework?
Thanks for porting Ash to JS!

**Comment by JulianG** [comment]
Duh! I just saw the other repos where you keep the examples.

**Comment by BrettJephson** [comment]
Cool, I was just about to answer:

Simple answer: yes. 

I need to write up some docs and getting started type information but, for now, I have ported the original asteroids example from the Actionscript 3 version of Ash. This can be found at: 

https://github.com/brejep/ashjs-asteroids-example

I am also working on a more extensive platformer game example, early code can be found at:

https://github.com/brejep/ashjs-platformer-example

Also, http://www.ashframework.org/ has some more tutorials and articles about the original Actionscript 3 version of the framework and most of that information applies to the javascript version too.

**Comment by JulianG** [comment]
Awesome! Thanks!
