### ISSUE TITLE
Node sanitation issue from As3 version

### ISSUE THREAD

**Issue by jusopi** [BrettJephson/ash-js#8]
This may or may not be similar to the entity not being removed from the system.  Basically there was a bug in the as3 version where when you destroyed an entity, associated nodes kept reference to the entity until that node was used for a newly created entity.

Since the js port of Ash was created before the as3 issue was resolved, it's quite possible the faulty logic was also ported over.  

There is an extensive conversation as well as tests for the as3 version here -https://groups.google.com/forum/?hl=en#!topic/ash-framework/SIlNf9ifA1E

Here was the fix for the as3 version addressed by Mr. Lord - https://github.com/richardlord/Ash/commit/dfa978fd6059135b301017fa5d1e8f1c5de4673f

**Comment by BrettJephson** [comment]
Issue looks like it is to do with the NodePool class specifically. 

Current port is prior to the NodePool being added. I was close to finishing an update with NodePool and the state machine improvements that are in the current AS3 version. I'll make sure this fix is in there when I add the feature.

**Comment by BrettJephson** [comment]
Sorry, I didn't think the NodePool was already in the repo but it is. I'll look at adding the fix to it. 

Thanks

**Comment by BrettJephson** [comment]
Implemented the fix from the AS3 version.

**Comment by jusopi** [comment]
UPDATE:
Nevermind, I'm an idiot, was looking at the wrong folder. Sorry.

Curious, looking at the github i want to grab the latest but not seeing that the min version has been updated.  I still don't have a handle on your build processes.  Will you be uploading a new version of the builds?
