### ISSUE TITLE
grunt optimization problem?

### ISSUE THREAD

**Issue by brodavi** [BrettJephson/ash-js#9]
Hi, thanks for the ash-js lib!

So I pulled the repo and did a grunt build, but there appears to be some problems.

/build/ashteroids.js
line 972, the empty array argument is missing
line 2442, 'ash' and the empty array are missing. instead,:

define("ash", function(){});

is inserted at line 2448

these (optimization?) changes are seemingly problematic.

**Comment by BrettJephson** [comment]
Hi, are you getting this error when you build ash-js? Did you use a particular grunt task? I've just tried running grunt and had no problems. 

Or is the problem when you use the built javascript file with the Ashteroids example project?

Please clarify and I'll try to get any issues sorted as soon as possible.

Thanks.

**Comment by brodavi** [comment]
Oops... yes, it was with the ashteroids example project, not ash-js, sorry.

The task is simply 'grunt'
